version: '3'
services:
  redis:
    image: redis:4.0-alpine
    container_name: redis
    volumes:
      - redis_data:/data:delegated
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
    links: 
      - redis
volumes:
  redis_data: