"""empty message

Revision ID: 54496fa112e0
Revises: 
Create Date: 2020-08-02 15:29:24.342675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54496fa112e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iot', sa.Column('forecast_value', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iot', 'forecast_value')
    # ### end Alembic commands ###
